services:
  paperless_email_processor:
    env_file:
      - path: ./.env
    build: .
    container_name: paperless_email_processor
    labels:
      # This label is used by Watchtower not update this container
      - "com.centurylinklabs.watchtower.enable=false"
    # environment:
    #   - PAPERLESS_API_TOKEN=${PAPERLESS_API_TOKEN}
    #   - PAPERLESS_API_PATH=${PAPERLESS_API_PATH}
    #   - PAPERLESS_API_URL=${PAPERLESS_API_URL}
    #   - SMTP_PORT=${SMTP_PORT}
    #   - SMTP_SRV=${SMTP_SRV}
    #   - SMTP_USR=${SMTP_USR}
    #   - SMTP_PWD=${SMTP_PWD}
    #   - SMTP_TO=${SMTP_TO}
    volumes:
      - ${PROCESS_FOLDER}:/app/process_folder
    restart: unless-stopped
