version: "3"

dotenv:
  - .env

vars:
  DOCKER_IMAGE: paperless_email_processor
  REMOTE_PATH: "/Volumes/docker/{{.DOCKER_IMAGE}}"

tasks:
  default:
    cmd: task -l --sort none
    silent: true

  up:
    desc: Start the {{.DOCKER_IMAGE}} docker compose service
    cmds:
      - "{{.SUDO}} docker compose up -d"

  down:
    desc: Stop the {{.DOCKER_IMAGE}} docker compose service
    cmds:
      - "{{.SUDO}} docker compose down"

  rebuild:
    desc: Rebuild the {{.DOCKER_IMAGE}} docker compose service
    cmds:
      - "{{.SUDO}} docker compose up -d --build"

  rmi:
    desc: Stop the {{.DOCKER_IMAGE}} docker compose service
    cmds:
      - "{{.SUDO}} docker compose down --rmi all"

  logs:
    desc: Show logs for the {{.DOCKER_IMAGE}} service
    cmds:
      - "{{.SUDO}} docker compose logs -f {{.DOCKER_IMAGE}}"

  run:
    desc: Run the script with uv
    cmds:
      - uv run main.py

  sync:
    desc: "Sync the files to the remote system"
    cmds:
      - rsync -avz . --exclude '.ruff_cache/' --exclude '__pycache__/'  --exclude '.git' --exclude '.venv' --exclude '.env' --exclude '.envrc' --exclude '.vscode' --exclude '.pytest_cache' --exclude 'paperless_email_processor.log' --exclude 'process_folder/' {{.REMOTE_PATH}}/
